### ISSUE TITLE
Error while trying to npm run dev (scss) Wrong number of arguments (1 for 0) for `form-control-focus'

### ISSUE THREAD

**Issue by necony286** [zackproser/argon-portfolio#1]
after git cloning and running 
`npm install`
then when i tried to run 
`npm run dev`
I keep getting this error:

ERROR  Failed to compile with 1 errors               friendly-errors 11:43:32

 ERROR  in ./assets/argon/scss/argon.scss             friendly-errors 11:43:32

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in /home/necony286/Documents/projects/argon-portfolio/node_modules/bootstrap/scss/_forms.scss (line 40, column 12)
                                                      friendly-errors 11:43:32
 @ ./assets/argon/scss/argon.scss 4:14-234 14:3-18:5 15:22-242
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js

**Comment by mogalmahesh** [comment]
Any Update on this? I am facing the same issue.

**Comment by Belgi1000** [comment]
Me too

**Comment by wfabritius** [comment]
Pasted solution from another project: 
https://github.com/creativetimofficial/ct-nuxt-argon-dashboard-pro/issues/9

> As a fix please change this
> "bootstrap": "^4.3.1" to this "bootstrap": "4.3.1"
> in package json.
> 
> Npm especially will install the latest version of bootstrap which is 4.4.1 and has some changes in the sass files. Making sure you install 4.3.1 will fix the issue

**Comment by gkkirilov** [comment]
@wfabritius Thanks it worked like a charm

**Comment by zackproser** [comment]
Thanks @wfabritius - I can confirm this worked for me as well.
